# Trial Name: qc.yaml
# ARIAC2023

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]

parts:  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'pump'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin6:
      - type: 'battery'
        color: 'blue'
        slots: [1, 3, 7, 9]

challenges:
  - dropped_part:
      robot: 'floor_robot'
      type: 'battery'
      color: 'blue'
      drop_after: 1 # drops the 2nd part the robot successfully picks
      delay: 5 # drops after 5 seconds

orders:
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'blue'
          quadrant: 1
        - type: 'battery'
          color: 'blue'
          quadrant: 2
        - type: 'battery'
          color: 'blue'
          quadrant: 3
        - type: 'battery'
          color: 'blue'
          quadrant: 4