# Trial Name: faulty_part_sample.yaml
# ENPM663

time_limit: 400 # options: -1 (no time limit) or number of seconds (max 500)

# PART SETUP
parts:
  agvs:
    agv1:
      tray_id: 0
      parts:
        - type: 'pump'
          color: 'green'
          quadrant: 1
          rotation: 0
  
        
# CHALLENGE SETUP
challenges:
  - faulty_part:
      order_id: 'MMB30H00'
      quadrant1: true
      

# ORDER SETUP
orders:
  - id: 'MMB30H00'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 0
      destination: 'warehouse'
      products:
        - type: 'pump'
          color: 'green'
          quadrant: 1
