# Trial Name: qc.yaml
# ARIAC2023

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [3, 8] 
  slots: [1, 4]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin2:
      - type: 'pump'
        color: 'purple'
        slots: [1, 3, 7, 9]
    bin5:
      - type: 'battery'
        color: 'red'
        slots: [4]
      - type: 'regulator'
        color: 'red'
        slots: [6]
    bin1:
      - type: 'sensor'
        color: 'red'
        slots: [4]
      - type: 'pump'
        color: 'red'
        slots: [6]


orders:
  - id: '2IZJP127'
    type: 'combined'
    announcement:
      time_condition: 30
    priority: false
    combined_task:
      station: 'as1'
      products:
        - type: 'regulator'
          color: 'red'
          assembled_pose: 
            xyz: [0.175, -0.223, 0.215]
            rpy: ['pi/2', 0, '-pi/2']
          assembly_direction: [0, 0, -1]
        - type: 'battery'
          color: 'red'
          assembled_pose: 
            xyz: [-0.15, 0.035, 0.043]
            rpy: [0, 0, 'pi/2']
          assembly_direction: [0, 1, 0]
        - type: 'pump'
          color: 'red'
          assembled_pose: 
            xyz: [0.14, 0.0, 0.02]
            rpy: [0, 0, '-pi/2']
          assembly_direction: [0, 0, -1]
        - type: 'sensor'
          color: 'red'
          assembled_pose: 
            xyz: [-0.1, 0.395, 0.045]
            rpy: [0, 0, '-pi/2']
          assembly_direction: [0, -1, 0]
  - id: 'MMB30H56'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 3
      destination: 'warehouse'
      products:
        - type: 'pump'
          color: 'purple'
          quadrant: 1