# Trial Name: qc.yaml
# ARIAC2023

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [1] 
  slots: [2]

parts:
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'pump'
        color: 'green'
        slots: [2, 3]
    bin2:
      - type: 'battery'
        color: 'orange'
        slots: [5]
    bin3:
      - type: 'regulator'
        color: 'red'
        slots: [6, 7]
orders:
  - id: 'LUFFY1232'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 4
      tray_id: 1
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'orange'
          quadrant: 1
        - type: 'pump'
          color: 'green'
          quadrant: 2
        - type: 'regulator'
          color: 'red'
          quadrant: 3
        - type: 'pump'
          color: 'green'
          quadrant: 4