# Trial Name: rwa4.yaml

# ENVIRONMENT SETUP

time_limit: -1 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [1, 2] 
  slots: [1, 2]


parts:  
  bins: # bin params - 8 total bins each bin has nine total slots (1-9)
    bin1:
      - type: 'battery'
        color: 'red'
        slots: [1]
    bin2:
      - type: 'battery'
        color: 'red'
        slots: [2]
    bin5:
      - type: 'battery'
        color: 'orange'
        slots: [3]
    bin6:
      - type: 'battery'
        color: 'orange'
        slots: [4]

orders:
  - id: 'KITTING1'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 1
      tray_id: 2
      destination: 'warehouse'
      products:
        - type: 'battery'
          color: 'red'
          quadrant: 1
        - type: 'battery'
          color: 'red'
          quadrant: 2
        - type: 'battery'
          color: 'orange'
          quadrant: 3
        - type: 'battery'
          color: 'orange'
          quadrant: 4