# Trial Name: sensor_blackout_sample.yaml
# ENPM663

time_limit: 400 # options: -1 (no time limit) or number of seconds (max 500)

kitting_trays: # Which kitting trays will be spawn
  tray_ids: [1, 1] 
  slots: [2, 3]

# PART SETUP
parts:
  bins:
    bin5:
      - type: 'sensor'
        color: 'purple'
        slots: [2, 3, 4]
        rotation: 'pi/6'
  
        
# CHALLENGE SETUP
challenges:
  - sensor_blackout:
      duration: 5.0
      sensors_to_disable: ['logical_camera']
      # submission_condition:
        # order_id: 'MMB30H00'
      time_condition: 10
      # part_place_condition:
      #   type: 'sensor'
      #   color: 'purple'
      #   agv: 2

      

# ORDER SETUP
orders:
  - id: 'MMB30H00'
    type: 'kitting'
    announcement:
      time_condition: 0
    priority: false
    kitting_task:
      agv_number: 2
      tray_id: 1
      destination: 'warehouse'
      products:
        - type: 'sensor'
          color: 'purple'
          quadrant: 1
        - type: 'sensor'
          color: 'purple'
          quadrant: 2